config/routes.rb
Rails.application.routes.draw do
  root to: "prospects#index"
  resources :conversations
  resources :prospects
  resources :statuses
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :prospect
end

app/models/prospect.rb
class Prospect < ApplicationRecord
  belongs_to :status
  belongs_to :user
  has_many :conversations, dependent: :destroy
  validates :nombre, :apellido, :email, presence: { message: "El campo debe existir" }
end

app/models/status.rb
class Status < ApplicationRecord
    has_many :prospects
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: %i[ show edit update destroy ]

  # GET /conversations or /conversations.json
  def index
    @conversations = Conversation.all
  end

  # GET /conversations/1 or /conversations/1.json
  def show    
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new  
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations or /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to prospects_path, notice: "La conversación fue creada exitosamente." }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1 or /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: "Conversation was successfully updated." }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1 or /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: "Conversation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
      #@prospect = Prospect.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conversation_params
      params.require(:conversation).permit(:detalle, :prospect_id)
    end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: %i[ show edit update destroy ]

  # GET /prospects or /prospects.json
  def index
    @prospects = Prospect.all.order(id: :desc)
  end

  # GET /prospects/1 or /prospects/1.json
  def show
    @conversations = Conversation.where(prospect_id: @prospect.id)
    @conversation = Conversation.new
  end

  # GET /prospects/new
  def new
    @prospect = Prospect.new
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects or /prospects.json
  def create
    @prospect = Prospect.new(prospect_params)

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to @prospect, notice: "El prospecto fue creado exitosamente." }
        format.json { render :show, status: :created, location: @prospect }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1 or /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to @prospect, notice: "El prospecto fue actualizado exitosamente." }
        format.json { render :show, status: :ok, location: @prospect }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1 or /prospects/1.json
  def destroy
    @prospect.destroy
    respond_to do |format|
      format.html { redirect_to prospects_url, notice: "El prospecto fue eliminado exitosamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prospect_params
      params.require(:prospect).permit(:nombre, :apellido, :telefono, :email, :status_id, :user_id)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ show edit update destroy ]

  # GET /statuses or /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1 or /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses or /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: "Status was successfully created." }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1 or /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: "Status was successfully updated." }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1 or /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: "Status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:estado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/conversations/_form.html.erb
<%= form_with(model: conversation) do |form| %>
  <% if conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% conversation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :detalle %>
    <%= form.text_field :detalle %>
  </div>

  <div class="row">
    <div class="col-3">      
      <%= form.hidden_field :prospect_id, :value => @prospects %>   
    </div>
  </div>

 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conversations</h1>

<table>
  <thead>
    <tr>
      <th>Detalle</th>
      <th>Prospect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.detalle %></td>
        <td><%= conversation.prospect_id %></td>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Detalle:</strong>
  <%= @conversation.detalle %>
</p>

<p>
  <strong>Prospect:</strong>
  <%= @conversation.prospect_id %>
</p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM-TD</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <p class="navbar-brand">CRM-TD</p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <% if user_signed_in? %>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">            
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Inicio</a>
              </li>
            </ul>  
            <span class="navbar-text">            
              <%= link_to "Cerrar Sesion ", destroy_user_session_path, method: :delete, :class => "nav-link" %>                  
            </span> 
          <% else %>
            
          <% end %>            
        </div>
      </div>
    </nav>

    <div class="container">

    <%= yield %>

    </div>

    <footer class="py-5 bg-black">
      <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; www.sala45.cl | 2022 | Marcela Arce Reyes</p></div>
    </footer>

  </body>
</html>

app/views/prospects/_form.html.erb
<%= form_with(model: prospect) do |form| %>
  <% if prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
        <% prospect.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <%= form.label :nombre %>
      <div class="col-3">
        <%= form.text_field :nombre, class: "form-control" %>
      </div>
  </div>


  <div class="row">
    <%= form.label :apellido %>
      <div class="col-3">
        <%= form.text_field :apellido, class: "form-control" %>
      </div>
  </div>

  <div class="row">
    <%= form.label :telefono %>
      <div class="col-3">
        <%= form.text_field :telefono, class: "form-control" %>
      </div>
  </div>

  <div class="row">
    <%= form.label :email %>
      <div class="col-3">
        <%= form.text_field :email, class: "form-control" %>
      </div>
  </div>

  <div class="row">
    <%= form.label :status_id, "Estado" %>
      <div class="col-3">
        <%= form.collection_select :status_id, Status.all, :id, :estado, include_blank: "Elige un Estado", class: "form-control" %>
      </div>
  </div>

  <div class="row">
    <div class="col-3">
      <% if current_user %>
        <%= form.hidden_field :user_id, value: current_user.id %>
      <% end %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="actions">
      <%= form.submit "Crear Prospecto", :class => "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/prospects/edit.html.erb
<h1>Editar Prospecto</h1>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Regresar', prospects_path, class: "btn btn-danger" %>

app/views/prospects/index.html.erb
<h3 id="notice"><%= notice %></h3>

<div class="text-center">
  <h1>Prospectos | <%= link_to 'Crear nuevo', new_prospect_path%></h1>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4 text-center">
  <div class="col">
    <div class="card text-white bg-success">
      <div class="card-body">        
        <h1 class="card-text"><%= Prospect.where(status_id: 1).count %></h1>
        <h4 class="card-title">Prospecto</h4>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card text-white bg-success">      
      <div class="card-body">        
        <h1 class="card-text"><%= Prospect.where(status_id: 2).count %></h1>
        <h4 class="card-title">Interesado</h4>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card text-white bg-success">
      <div class="card-body">        
        <h1 class="card-text"><%= Prospect.where(status_id: 3).count %></h1>
        <h4 class="card-title">Cliente</h4>
      </div>
    </div>
  </div>   
</div>

<br>

<table class= "table text-center">
  <thead>
    <tr class="table-dark">
      <th>ID</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefono</th>
      <th>Email</th>
      <th>Estado</th>
      <th>Creado por</th>      
      <th>Fecha Ingreso</th>
      <th>Conversaciones</th>
      <th colspan="3"> Acciones </th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <tr>
        <td><%= prospect.id %></td>
        <td><%= prospect.nombre %></td>
        <td><%= prospect.apellido %></td>
        <td><%= prospect.telefono %></td>
        <td><%= prospect.email %></td>
        <td><%= prospect.status.estado %></td>
        <td><%= prospect.user.email %></td>        
        <td><%= prospect.created_at.to_date %></td>
        <td><%= prospect.conversations.count%><i class="far fa-comment-dots"></i></td>
        

        <td><%= link_to '<i class="far fa-eye"></i>'.html_safe, prospect %></td>
        <td><%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_prospect_path(prospect) %></td>
        <td><%= link_to '<i class="far fa-times-circle"></i>'.html_safe, prospect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/prospects/new.html.erb
<h1>Nuevo Prospecto</h1>

<%= render 'form', prospect: @prospect %>

<%= link_to 'Regresar', prospects_path, class: "btn btn-danger" %>

app/views/prospects/show.html.erb
<h3 id="notice"><%= notice %></h3>

<div class="card card-custom gutter-b">
  <div class="card-header">
    <div class="card-title">
      <h1>Información del Prospecto</h1>
    </div>    
  </div>
  <div class="card-body">
    <br>
    <div>
      <p>
        <strong>Nombre:</strong>
        <%= @prospect.nombre %>
      </p>

      <p>
        <strong>Apellido:</strong>
        <%= @prospect.apellido %>
      </p>

      <p>
        <strong>Telefono:</strong>
        <%= @prospect.telefono %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @prospect.email %>
      </p>

      <p>
        <strong>Estado:</strong>
        <%= @prospect.status.estado %>
      </p>

    </div>   
  </div>    
    
  <table class= "table text-center">
    <thead>
      <tr class="table-secondary">
        <th>Fecha Ingreso</th>
        <th>Conversaciones</th>
      </tr>
    </thead>

    <tbody>  
      <% @conversations.each do |c| %>
      <tr>
        <td><%= c.created_at.to_date %></td>
        <td><%= c.detalle %></td>        
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= form_with(model: @conversation) do |form| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
        <% @conversation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= form.label :detalle, "Ingresar una nueva conversacion con el cliente" %></strong>
    <%= form.text_area :detalle, class: "form-control" %>
  </div>

  <div class="row">
    <div class="col-3">      
      <%= form.hidden_field :prospect_id, :value => @prospect.id %>   
    </div>
  </div> 

  <div class="actions">
    <%= form.submit "Crear nueva conversacion", class: "btn btn-success" %>
  </div>
<% end %>

</div>   

<%= link_to 'Regresar', prospects_path, class: "btn btn-danger" %>

app/views/statuses/_form.html.erb
<%= form_with(model: status) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
        <% status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.estado %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado:</strong>
  <%= @status.estado %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>